server.port: 8443

spring:
  cloud:
    gateway:
      routes:
        - id: eureka-api
          uri: http://${eureka:eureka}:8761
          predicates:
            - Path=/eureka/api/{segment}
          filters:
            - SetPath=/eureka/{segment}

        - id: eureka-web-start
          uri: http://${eureka:eureka}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-web-other
          uri: http://${eureka:eureka}:8761
          predicates:
            - Path=/eureka/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: config-file
          uri: ${spring.cloud.config.uri}
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*), /$\{segment}

        - id: foodie-diner-service
          uri: lb://foodie-diner-service
          predicates:
            - Path=/diner/**
          filters:
            - StripPrefix=1

        - id: foodie-order-service
          uri: lb://foodie-order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1

        - id: foodie-follow-service
          uri: lb://foodie-follow-service
          predicates:
            - Path=/follow/**
          filters:
            - StripPrefix=1

        - id: foodie-feed-service
          uri: lb://foodie-feed-service
          predicates:
            - Path=/feed/**
          filters:
            - StripPrefix=1

        - id: foodie-point-service
          uri: lb://foodie-point-service
          predicates:
            - Path=/point/**
          filters:
            - StripPrefix=1

        - id: foodie-restaurant-service
          uri: lb://foodie-restaurant-service
          predicates:
            - Path=/restaurant/**
          filters:
            - StripPrefix=1

management.endpoint.gateway.enabled: true


