server:
  port: 8081

spring:
  application:
    name: foodie-diner
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/foodie-cloud?connectTimeout=2000&socketTimeout=150000&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    port: 6379
    host: localhost
    timeout: 3000
    password: 123456

security:
  oauth2:
    client:
      client-id: appId
      client-secret: 123456
    resource:
      token-info-uri: http://localhost:8082/oauth/check_token
      prefer-token-info: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

mybatis:
  configuration:
    map-underscore-to-camel-case: true

feign:
  oauth2:
    enabled: true
    load-balanced: true
  client:
    config:
      default:
        loggerLevel: BASIC
  httpclient:
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
    ok-http:
      read-timeout: 5s
  okhttp:
    enabled: true
    loadbalancer:
      enabled: true

