server:
  port: 8081

spring:
  application:
    name: foodie-diner
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/foodie-cloud?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
  redis:
    port: 6379
    host: localhost
    timeout: 3000
    password: 123456

security:
  oauth2:
    client:
      client-id: appId
      client-secret: 123456
    resource:
      token-info-uri: http://localhost:8082/oauth/check_token
      prefer-token-info: true

service:
  name:
    foodie-oauth-server: http://foodie-oauth2-server/
    foodie-point-server: http://foodie-point/

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

mybatis:
  configuration:
    map-underscore-to-camel-case: true

debug: on
