version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=true --lower_case_table_names=1 --tls-version=''
    healthcheck:
      test: "/usr/bin/mysql --user=${MYSQL_USR} --password=${MYSQL_PASSWORD} -e 'SHOW DATABASES;'"
      interval: 5s
      timeout: 2s
      retries: 10

  redis:
    image: redis:7
    restart: always
    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.11.8-management
    restart: always
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 2s
      retries: 60

  activemq:
    image: symptoma/activemq:latest
    restart: always
    env_file:
      - .env
    ports:
      - "61616:61616"
      - "8161:8161"


  #  monitor:
  #    build:
  #      context: monitor
  #    image: chensoul/monitor
  #    restart: always
  #    env_file:
  #      - .env
  #    ports:
  #      - "5100:5100"
  #
  #  xxljob:
  #    build:
  #      context: xxljob
  #    image: chensoul/xxljob
  #    restart: always
  #    env_file:
  #      - .env
  #    ports:
  #      - "5200:5200"
  #
  #  sentinel:
  #    build:
  #      context: sentinel
  #    image: chensoul/sentinel
  #    restart: always
  #    env_file:
  #      - .env
  #    ports:
  #      - "5300:5300"

  eureka:
    build:
      context: platform/eureka
    image: chensoul/eureka
    restart: always
    env_file:
      - .env
    ports:
      - "8761:8761"

  gateway:
    build:
      context: platform/gateway
    image: chensoul/gateway
    restart: always
    env_file:
      - .env
    ports:
      - "8443:8443"

  auth-center:
    build:
      context: platform/auth-center/auth-center-service
    image: chensoul/auth-center
    restart: always
    env_file:
      - .env
    ports:
      - "6000:6000"

  foodie-diner:
    build:
      context: foodie-diner
    image: chensoul/foodie-diner
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8081"

  foodie-point:
    build:
      context: foodie-point/foodie-point-service
    image: chensoul/foodie-point
    restart: always
    env_file:
      - .env
    ports:
      - "8082:8082"

  foodie-order:
    build:
      context: foodie-order
    image: chensoul/foodie-order
    restart: always
    env_file:
      - .env
    ports:
      - "8083:8083"

  foodie-follow:
    build:
      context: foodie-follow/foodie-follow-service
    image: chensoul/foodie-follow
    restart: always
    env_file:
      - .env
    ports:
      - "8084:8084"

  foodie-feed:
    build:
      context: foodie-feed/foodie-feed-service
    image: chensoul/foodie-feed
    restart: always
    env_file:
      - .env
    ports:
      - "8085:8085"

  foodie-restaurant:
    build:
      context: foodie-restaurant
    image: chensoul/foodie-restaurant
    restart: always
    env_file:
      - .env
    ports:
      - "8086:8086"
