version: '3.8'
services:
  register:
    build:
      context: register
    image: register
    restart: always
    env_file:
      - .env
    ports:
      - "8761:8761"

  gateway:
    build:
      context: gateway
    image: gateway
    restart: always
    env_file:
      - .env
    ports:
      - "8443:8443"

  foodie-auth:
    build:
      context: foodie-auth/foodie-auth-service
    image: foodie-auth
    restart: always
    env_file:
      - .env
    ports:
      - "6000:6000"

  foodie-diner:
    build:
      context: foodie-diner/foodie-diner-service
    image: foodie-diner
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8081"

  foodie-point:
    build:
      context: foodie-point/foodie-point-service
    image: foodie-point
    restart: always
    env_file:
      - .env
    ports:
      - "8082:8082"

  foodie-order:
    build:
      context: foodie-order
    image: foodie-order
    restart: always
    env_file:
      - .env
    ports:
      - "8083:8083"

  foodie-follow:
    build:
      context: foodie-follow/foodie-follow-service
    image: foodie-follow
    restart: always
    env_file:
      - .env
    ports:
      - "8084:8084"

  foodie-feed:
    build:
      context: foodie-feed/foodie-feed-service
    image: foodie-feed
    restart: always
    env_file:
      - .env
    ports:
      - "8085:8085"

  foodie-restaurant:
    build:
      context: foodie-restaurant
    image: foodie-restaurant
    restart: always
    env_file:
      - .env
    ports:
      - "8086:8086"

  monitor:
    build:
      context: monitor
    image: monitor
    restart: always
    env_file:
      - .env
    ports:
      - "5100:5100"

  xxljob:
    build:
      context: xxljob
    image: xxljob
    restart: always
    env_file:
      - .env
    ports:
      - "5200:5200"

  sentinel:
    build:
      context: sentinel
    image: sentinel
    restart: always
    env_file:
      - .env
    ports:
      - "5300:5300"

  mysql:
    image: mysql:8
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PWD}
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysql","-e", "SHOW DATABASES;" ]
      interval: 5s
      timeout: 2s
      retries: 10

  redis:
    image: redis:7
    restart: always
    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai
    command: redis-server --requirepass ${REDIS_PWD}
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.11.8-management
    restart: always
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PWD}
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 2s
      retries: 60

  activemq:
    image: symptoma/activemq:latest
    restart: always
    env_file:
      - .env
    ports:
      - "61616:61616"
      - "8161:8161"
