version: '3.8'

services:
  foodie-diner:
    build:
      context: foodie-diner/foodie-diner-service
    image: chensoul/foodie-diner
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8081"

  foodie-point:
    build:
      context: foodie-point/foodie-point-service
    image: chensoul/foodie-point
    restart: always
    env_file:
      - .env
    ports:
      - "8082:8082"

  foodie-order:
    build:
      context: foodie-order/foodie-order-service
    image: chensoul/foodie-order
    restart: always
    env_file:
      - .env
    ports:
      - "8083:8083"

  foodie-follow:
    build:
      context: foodie-follow/foodie-follow-service
    image: chensoul/foodie-follow
    restart: always
    env_file:
      - .env
    ports:
      - "8084:8084"

  foodie-feed:
    build:
      context: foodie-feed/foodie-feed-service
    image: chensoul/foodie-feed
    restart: always
    env_file:
      - .env
    ports:
      - "8085:8085"

  foodie-restaurant:
    build:
      context: foodie-restaurant/foodie-restaurant-service
    image: chensoul/foodie-restaurant
    restart: always
    env_file:
      - .env
    ports:
      - "8086:8086"

  mysql:
    image: mysql:8
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=true --lower_case_table_names=1 --tls-version=''
    healthcheck:
      test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} -e 'SHOW DATABASES;'"
      interval: 5s
      timeout: 2s
      retries: 10

  mysql-master:
    image: mysql:8
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=true --lower_case_table_names=1 --tls-version='' --log-bin=mysql-bin --server-id=1
    healthcheck:
      test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} -e 'SHOW DATABASES;'"
      interval: 5s
      timeout: 2s
      retries: 10

  mysql-slave:
    image: mysql:8
    restart: always
    env_file:
      - .env
    ports:
      - "3308:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=true --lower_case_table_names=1 --tls-version='' --log-bin=mysql-bin --server-id=2
    healthcheck:
      test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} -e 'SHOW DATABASES;'"
      interval: 5s
      timeout: 2s
      retries: 10

  redis:
    image: redis:7
    restart: always
    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.11.8-management
    restart: always
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 2s
      retries: 60

  activemq:
    image: symptoma/activemq:latest
    restart: always
    env_file:
      - .env
    ports:
      - "61616:61616"
      - "8161:8161"


  #  monitor:
  #    build:
  #      context: monitor
  #    image: chensoul/monitor
  #    restart: always
  #    env_file:
  #      - .env
  #    ports:
  #      - "5100:5100"
  #
  #  xxljob:
  #    build:
  #      context: xxljob
  #    image: chensoul/xxljob
  #    restart: always
  #    env_file:
  #      - .env
  #    ports:
  #      - "5200:5200"
  #
  #  sentinel:
  #    build:
  #      context: sentinel
  #    image: chensoul/sentinel
  #    restart: always
  #    env_file:
  #      - .env
  #    ports:
  #      - "5300:5300"

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  zipkin:
    image: openzipkin/zipkin:2.24.0
    restart: always
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"

  eureka:
    build:
      context: platform/eureka
    image: chensoul/eureka
    restart: always
    env_file:
      - .env
    ports:
      - "8761:8761"

  gateway:
    build:
      context: platform/gateway
    image: chensoul/gateway
    restart: always
    env_file:
      - .env
    ports:
      - "8443:8443"

  auth-service:
    build:
      context: platform/auth/auth-service
    image: chensoul/auth-service
    restart: always
    env_file:
      - .env
    ports:
      - "6666:6666"
    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost:6666/actuator/health" ]
      interval: 5s
      timeout: 2s
      retries: 10

  config-file:
    build: platform/config-file
    image: chensoul/config-file
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=default,native
    ports:
      - "8888:8888"
    volumes:
      - $PWD/config-repo:/config-repo
