spring.application.name: @artifactId@

# 默认连接到 http://localhost:8888
spring.config.import: "optional:configserver:"

spring:
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://${config-file:config-file}:8888
    username: ${SPRING_SECURITY_USER_NAME:root}
    password: ${SPRING_SECURITY_USER_PASSWORD:123456}
