server:
  port: 8761

spring:
  application:
    name: registry

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #服务端是否开启自我保护机制 （默认true）
    enableSelfPreservation: false
    #扫描失效服务的间隔时间（单位毫秒，默认是60*1000)
    evictionIntervalTimerInMs: 2000
    # from: https://github.com/spring-cloud-samples/eureka/blob/master/src/main/resources/application.yml
    waitTimeInMsWhenSyncEmpty: 0
    responseCacheUpdateIntervalMs: 5000
