server:
  port: 8085

spring:
  application:
    name: foodie-feed
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/foodie-cloud?connectTimeout=2000&socketTimeout=150000&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    port: 6379
    host: localhost
    timeout: 3000
    password: 123456

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

service:
  name:
    foodie-user: http://foodie-user/
    foodie-follow: http://foodie-follow/

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射
