server:
  port: 8085

spring:
  application:
<<<<<<< HEAD:foodie-feeds/src/main/resources/application.yml
    name: foodie-feeds
  datasource:
||||||| dbdbe77:foodie-feeds/src/main/resources/application.yml
    name: foodie-feeds
    datasource:
=======
    name: foodie-feed
    datasource:
>>>>>>> feature/07-points:foodie-feed/src/main/resources/application.yml
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/foodie-cloud?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
  redis:
    port: 6379
    host: localhost
    timeout: 3000
    password: 123456

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

service:
  name:
    foodie-oauth-server: http://foodie-oauth2-server/
    foodie-diner-server: http://foodie-diner/
    foodie-follow-server: http://foodie-follow/

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射
