server:
  port: 80

spring:
  application:
    name: foodie-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: foodie-user
          uri: lb://foodie-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: foodie-auth
          uri: lb://foodie-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: foodie-order
          uri: lb://foodie-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1

        - id: foodie-follow
          uri: lb://foodie-follow
          predicates:
            - Path=/follow/**
          filters:
            - StripPrefix=1

        - id: foodie-feed
          uri: lb://foodie-feed
          predicates:
            - Path=/feed/**
          filters:
            - StripPrefix=1

        - id: foodie-point
          uri: lb://foodie-point
          predicates:
            - Path=/point/**
          filters:
            - StripPrefix=1

        - id: foodie-restaurant
          uri: lb://foodie-restaurant
          predicates:
            - Path=/restaurant/**
          filters:
            - StripPrefix=1

secure:
  ignore:
    urls:
      - /actuator/**
      - /auth/oauth/**
      - /diner/signin
      - /diner/send
      - /diner/checkPhone
      - /diner/register
      - /seckill/add
      - /restaurant/**

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
