server:
  port: 80

spring:
  application:
    name: foodie-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: foodie-diners
          uri: lb://foodie-diners
          predicates:
            - Path=/diners/**
          filters:
            - StripPrefix=1

        - id: foodie-oauth2-server
          uri: lb://foodie-oauth2-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

secure:
  ignore:
    urls:
      - /actuator/**
      - /auth/oauth/**
      - /diners/signin

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
