server:
  port: 8082

spring:
  application:
    name: foodie-oauth2-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/foodie-cloud?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
  redis:
    port: 6379
    host: localhost
    timeout: 3000
    password: 123456

client:
  oauth2:
    client-id: appId
    secret: 123456
    grant_types:
      - password
      - refresh_token
    token-validity-time: 3600
    refresh-token-validity-time: 3600
    scopes:
      - api
      - all

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射

management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露的端点
debug: on
